- name: Install dependencies
  apt:
    name: "{{item}}"
    state: latest
  become: "{{ should_become }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - wget
    - dirmngr
    - gnupg
    - software-properties-common

- name: Add an apt key for java8
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
  become: "{{ should_become }}"

- name: Add Java Repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
    state: present
  become: "{{ should_become }}"

- name: Install Oracle Java 8
  apt:
    name: adoptopenjdk-8-hotspot
    state: latest
  become: "{{ should_become }}"

- name: Install haveged
  apt:
    name: haveged
    state: latest
  become: "{{ should_become }}"